### ISSUE TITLE
Does this work with WebGLRenderingContext?

### ISSUE THREAD

**Issue by jonobr1** [antimatter15/jsgif#1]

**Comment by ranbuch** [comment]
Hi @deethee,
This link should help you:
http://stackoverflow.com/questions/32556939/saving-canvas-to-image-via-canvas-todataurl-results-in-black-rectangle#answers

Also to get the context you can always hijack createElement and getContext methods and save the context:

```javascript
        new function() {
				var orgCreateElement = document.createElement;
				// hijack createElement to hijack all the canvases getContext  
				Object.defineProperty(document, 'createElement', 
				{value: function(type) {
					var ans = orgCreateElement.apply(this, Array.prototype.slice.call(arguments));
					if (type == 'canvas') {
						var orgGetContext = ans.getContext;
						// hijack getContext to catch all the contexts and save then in window.mainContext (or wherever . . .) 
						ans.getContext = function() {
							if (!window.mainContext)
								window.mainContext = [];
							if (typeof arguments[1] === 'object')
								// set preserveDrawingBuffer = true will help you with canvas.toDataURL("image/png"); method
								arguments[1].preserveDrawingBuffer = true;
							var c = orgGetContext.apply(this, Array.prototype.slice.call(arguments));
							window.mainContext.push(c); 
							return c;
						};
					}
					return ans;
				}});
        }
```

That may be an overkill but just in case you're using some other framework (such as three.js) . . .
Make sure this code is running before any canvas has been created.
Your context is inside window.mainContext array.

Regarding @jonobr1 code unfortunately the browser always gets stuck in this line:
```javascript
encoder.addFrame(readBuffer, true);
```
with very high CPU hz

**Comment by ranbuch** [comment]
I've decided to go with that one:
https://github.com/yahoo/gifshot
while providing an images array with canvas.toDataURL("image/png") as images sources.

Works for me.
